### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by mikepurvis** [ros-infrastructure/catkin_pkg#113]
Would be great to have generated docs for this, either on RTD or http://docs.ros.org/independent/api/

**Comment by gavanderhoorn** [comment]
+1 to this, was just looking for them :).

**Comment by dirk-thomas** [comment]
I added a Makefile (9b8d30ed08c6f7692b38da2d2d9a3c6d6f4aeb9c) to generate the API docs: http://docs.ros.org/independent/api/catkin_pkg/

**Comment by gavanderhoorn** [comment]
Nice one, thanks.
