### ISSUE TITLE
catkin_create_meta_pkg

### ISSUE THREAD

**Issue by carlosjoserg** [ros-infrastructure/catkin_pkg#115]
I think the title is self-descriptive. 

An alternative could be to create an option to keep the pkg philosophy: `catkin_create_pkg --meta pkgname` (not sure, but the rest of options might be valid as well).

The idea is to have a template for meta packages, similar to what `catkin_create_pkg` does, just to make things easier and error-prone.

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request to add this new features.

**Comment by carlosjoserg** [comment]
Sure, and I will, but I typically ask before with an issue to see whether it is interesting or not (I can't label it as a question). Next time I will explain it in the issue as well.

I think I go for the `catkin_create_pkg --meta  pkgname` alternative, unless someone has any other idea.

**Comment by dirk-thomas** [comment]
From a short look to the `catkin_create_pkg` it seems that all arguments also make sense for meta packages. So adding a `--meta` options to the existing script seems like a good idea.
