### ISSUE TITLE
Change @{name} to ${PROJECT_NAME} in CMakeLists.txt.in template wherever possible

### ISSUE THREAD

**Issue by aleksandaratanasov** [ros-infrastructure/catkin_pkg#127]
Hi!

This concerns the CMakeLists.txt.in template used by catkin_create_pkg (https://github.com/ros-infrastructure/catkin_pkg/blob/master/src/catkin_pkg/templates/CMakeLists.txt.in). I have noticed that it hard-codes the package name chosen by the user everywhere, which I find somewhat tedious especially when I decide to change the name of the package. Wouldn't it be better to use the ${PROJECT_NAME} cmake variable instead? For example:

LIBRARIES @{name} -> LIBRARIES ${PROJECT_NAME}
target_link_libraries(@{name}_node ..) -> target_link_libraries(${PROJECT_NAME}_node ...)

Is there some deep meaning in hard-coding the name or is it something that was just left there from earlier versions of catkin_create_pkg?

Making this change will allow the user to make global changes for the whole package without the need of searching for every single @{name} and changing it.

**Comment by dirk-thomas** [comment]
Currently it is more a mixture of both ways: In some places (8 occurrences) the template already uses `${PROJECT_NAME}`. But in several other cases (11 occurrences) it uses `@{name}`.

I am a bit worried that the extra usage of variables makes it even more difficult to read for new users. But if you would like to create a PR replacing these instances I would be fine with merging it.

@tfoote @wjwwood What do you think about this?

**Comment by aleksandaratanasov** [comment]
Sure, I can do that. Will wait for some more opinions on this matter of course before I go with the pulling request. My current suggestion is to replace all @name occurrences except:

 - project(@name) - this obviously has to stay as it is
 - CPP files (for library, executable and gtest):
    - **add_library(${PROJECT_NAME} src/${PROJECT_NAME}/@name.cpp)**
    - **add_executable(${PROJECT_NAME}_node src/@{name}_node.cpp)**
    - **catkin_add_gtest(${PROJECT_NAME}-test test/test_@name.cpp)**

Source files are to be observed as constants here since they cannot be easily changed from within a CMakeLists.txt (yes, you can use the file manipulation commands to do that but this will make the shipped CMakeLists.txt even harder to read for new users) so their names should not depend on a variable such as @{PROJECT_NAME}.

**Comment by tfoote** [comment]
That sounds like a good approach.

**Comment by aleksandaratanasov** [comment]
Just created a pull request. Let me know if I have missed something.

**Comment by dirk-thomas** [comment]
Closed by #128. Thanks.
