### ISSUE TITLE
Travis CI problem?

### ISSUE THREAD

**Issue by JulianVolodia** [ros-infrastructure/catkin_pkg#134]
Hi.

I start to work with ROS, just going throught that page and... noticed that Travis status is unknown?

Best regards
![screenshot from 2015-12-14 06 56 27](https://cloud.githubusercontent.com/assets/1219023/11781492/d726c42a-a22f-11e5-86dd-62300f8471e5.png)

**Comment by dirk-thomas** [comment]
The page doesn't say that the status is unknown. It says that "there was an error while loading the data". It also tells you "please try again".

I get the following page so it looks all good: ![travis-catkin-pkg](https://cloud.githubusercontent.com/assets/1335366/11785995/1a0bf626-a239-11e5-810d-e3d6f5416e16.png)
