### ISSUE TITLE
catkin_generate_changelog: support custom release tags

### ISSUE THREAD

**Issue by NikolausDemmel** [ros-infrastructure/catkin_pkg#142]
I would like to use custom release tags in for `catkin_generate_changelog` just like for `catkin_prepare_release`.

I guess this is a case of "noone has gotten around to implement it yet".

As a workaround one can temporarily create a local tag of the form `x.y.z` of the latest release, run the script, then delete it again.

**Comment by tfoote** [comment]
Can you clarify what you're looking for? Running `catkin_generate_changelog` simply generates the section "Forthcoming" which is then replaced by `catkin_prepare_release` with the release tag. 

Like this `catkin_generate_changelog` (with manual cleanup): https://github.com/ros/geometry/commit/29a5664a4decb76f13e34df8be368fa28148c6ce
Then `catkin_prepare_release`: https://github.com/ros/geometry/commit/cb2361a784e6f3ff09930fe441d7f66cdc01b15d

**Comment by NikolausDemmel** [comment]
I'm looking for that exact functionality, but it seems to me that the current implementation of catkin_generate_changelog only works for release tags of form 'x.y.z', not something custom like 'foo-x.y.z', which the rest of the release toolchain, including catkin_prepare_release, and bloom-release does support. For calling_prepare_release you can use the `-t` command line parameter and for bloom the form of the release tag is part of the track configuration.

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request to implement this enhancement.

**Comment by gavanderhoorn** [comment]
I'm currently working on releasing a repository that has all tags prefixed with a `v`. As @NikolausDemmel mentioned, that is no problem for Bloom or `catkin_prepare_release`, but the automatically generated changelogs are empty.

Adding naive support for tag prefixes wasn't too hard, but I'm wondering what the desired behaviour is: should tag prefixes be stripped as soon as the tags are extracted from the repository (so `changelog_generator.sorted_tags(..)` and friends don't need to be updated), or should the tags be left in-tact, as they came from the `git log`? The former makes things rather easy, the latter is cleaner imho (but does require more changes).

I'm fine with stripping (losing the `v` isn't too much of an issue), but for the example @NikolausDemmel gave (`foo-..`), I'm not sure what the best approach is.

**Comment by 130s** [comment]
I believe I just hit the issue that is reported in this ticket. In my case veresion extracted from the previous tag [here](https://github.com/ros-infrastructure/catkin_pkg/blob/359d52faaf193c802aea0910398dff0dd0d5f5c4/src/catkin_pkg/changelog_generator.py#L97) is empty.

Looks like generating changelog depends on the VCS' tag. (Premature thought but) Instead, how about using a package version of previous release from package.xml? That way we could separate the format of VCS' `tag` and package.xml's `version` element.

**Comment by NikolausDemmel** [comment]
@gavanderhoorn, sorry I never replied here.

> I'm fine with stripping (losing the v isn't too much of an issue), but for the example @NikolausDemmel gave (`foo-..`), I'm not sure what the best approach is.

The use case I had (at my previous job) was for repo that most people were using in a non-ros context, so I had the tags as `catkin-x.y.z`, to be less intrusive / more explicit. So I would say your first suggestion that "tag prefixes be stripped as soon as the tags are extracted from the repository" make sense and is not limiting.

I don't have this use case any more, but a PR might still be helpful for others.

> Looks like generating changelog depends on the VCS' tag. (Premature thought but) Instead, how about using a package version of previous release from package.xml? That way we could separate the format of VCS' tag and package.xml's version element.

If it's automatic, all the better, but I guess having an explicit `-t` like for `catkin_prepare_release` would already work well enough for this uncommon usecase.

**Comment by 130s** [comment]
@NikolausDemmel @gavanderhoorn `version` tag in `package.xml` limits to x.y.z according to [REP0127](http://www.ros.org/reps/rep-0127.html#version) and [REP0140](http://www.ros.org/reps/rep-0140.html#version) for format 2. I'm just curious where you define the custom tags.

> The version number of the package in the format MAJOR.MINOR.PATCH where each part is numeric only.

**Comment by NikolausDemmel** [comment]
@130s, the ROS package version numbers are `x.y.z`, but the git tags in the source repo are `catkin-x.y.z`.

**Comment by dirk-thomas** [comment]
I will go ahead and close this ticket since there is no plan to work on this (hence the milestone untargeted in the past). Any contribution to support this use case is welcome though.
