### ISSUE TITLE
Dependency should have a hash function

### ISSUE THREAD

**Issue by mikepurvis** [ros-infrastructure/catkin_pkg#147]
Although they are not immutable, this is important for being able to deduplicate/manage them using `set()`. I'm monkey-patching in this one, but it'd be great to have it merge upstream:

```
import catkin_pkg.package
catkin_pkg.package.Dependency.__hash__ = lambda self: hash(tuple([getattr(self, slot) for slot in self.__slots__]))
```

**Comment by dirk-thomas** [comment]
That sounds good. Can you please make a pull request to add `__hash__`.

Depending on how it is used it might make sense to only use the name rather then all attributes. But i guess that could be unexpected in other cases.

**Comment by mikepurvis** [comment]
We explicitly want multiple distinct version requirements to not be de-duplicated in our bundle builds.

FWIW, the dpkg-buildpackage tooling handles eliminating redundant deps, eg this binary package stanza in the dsc control file:

```
Package: test
Architecture: amd64
Depends: python-catkin-tools (>= 0.3.1), python-catkin-tools (>= 0.4.0), python-catkin-tools
```

Will get collapsed down to this one in the deb:

```
Package: test
Architecture: amd64
Depends: python-catkin-tools (>= 0.4.0)
```

**Comment by dirk-thomas** [comment]
Please see #151 and comment if that suites your use case.
