### ISSUE TITLE
flake8 integration

### ISSUE THREAD

**Issue by Nickolaim** [ros-infrastructure/catkin_pkg#210]
I'd like to add flake8 integration to this project, as it is done in [https://github.com/ros-infrastructure/rosdep](https://github.com/ros-infrastructure/rosdep) - with a new unit test that runs flake8.

Ideas/objections?

**Comment by dirk-thomas** [comment]
Sounds like a good idea to me.

Looking at the `rosdep` repo I am not sure if all the flake8 tests works as expected since as far as I can see no plugin are being installed (though some like `I` are being ignored in the test)?

After the initial integration we should aim to reduce the ignores.

**Comment by Nickolaim** [comment]
[https://github.com/ros-infrastructure/rosdep/blob/master/test/test_flake8.py](https://github.com/ros-infrastructure/rosdep/blob/master/test/test_flake8.py) is the test.  It has few ignores.  When I was testing it, I saw the following rules enabled: ['E', 'F', 'W', 'C90'].

**Comment by Nickolaim** [comment]
I did the change at [https://github.com/Nickolaim/catkin_pkg/commit/bff2cb20665c0ff2bdc39ce8045543d01275a303](https://github.com/Nickolaim/catkin_pkg/commit/bff2cb20665c0ff2bdc39ce8045543d01275a303) and hit an interesting issue - flake8 does not work on python 3.2.6 for this project.  This is the link to [the Travis CI build](https://travis-ci.org/Nickolaim/catkin_pkg/builds/357220434). I hit the same issue on a local virtual environment v 3.2.6.  Interesting that there no problems on 3.3 and 3.6.

I am not sure what to do.  One way I see is to drop 3.2 from Travis CI job and replace it with 3.6.
