### ISSUE TITLE
catkin_prepare_release does not work in Python3

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/catkin_pkg#224]
It just says that there are uncommitted changes (even if there are not) and exits. I believe it has to do with subprocess returning bytes instead of a string in Python3, but I didn't have time to investigate further. I'm using the Python2 version for now. `catkin_generate_changelogs` may also have issues, but I was always using it from python2 because of when I update `catkin_pkg`.

**Comment by dirk-thomas** [comment]
Fix released in 0.4.4.
