### ISSUE TITLE
Unable to install 0.4.7 of  python-catkin-pkg for ROS Indigo

### ISSUE THREAD

**Issue by davidNguyenHTD** [ros-infrastructure/catkin_pkg#230]
Somehow we are no longer able to install python catkin pkg with apt-get. The log is attached:

```
sudo apt-get install python-catkin-pkg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  python-catkin-pkg-modules
The following packages will be upgraded:
  python-catkin-pkg python-catkin-pkg-modules
2 upgraded, 0 newly installed, 0 to remove and 652 not upgraded.
Need to get 0 B/44.4 kB of archives.
After this operation, 56.3 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg-deb: error: archive '/var/cache/apt/archives/python-catkin-pkg-modules_0.4.7-1_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/python-catkin-pkg-modules_0.4.7-1_all.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
dpkg-deb: error: archive '/var/cache/apt/archives/python-catkin-pkg_0.4.7-100_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/python-catkin-pkg_0.4.7-100_all.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/python-catkin-pkg-modules_0.4.7-1_all.deb
 /var/cache/apt/archives/python-catkin-pkg_0.4.7-100_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by dirk-thomas** [comment]
This looks like a duplicate of #227. Please try to make sure `dpkg` is up-to-date and close this ticket if that resolves your problem.

**Comment by davidNguyenHTD** [comment]
Thanks @dirk-thomas . Updating dpkg works. Thanks

**Comment by elahia** [comment]
I have the same issue, but updating dpkg didn't work for me,

**Comment by dirk-thomas** [comment]
@elahia You have been cross posting this in at least three locations:
* https://answers.ros.org/question/299739/problem-in-installing-ros-indigo-in-chroot/
* https://github.com/ros/catkin/issues/855#issuecomment-410675028

This is against the etiquette - please read the support support guidelines of ROS: http://wiki.ros.org/Support

**Comment by elahia** [comment]
Dear Drik,
 I'm sorry for this, but i see this is a common error with an easy solution that is not solvable for me! so i'm just trying to solve it, installing ros is so crucial for me regards to deadlines, and if i don't ask others what can i do!
Regards,

**Comment by dirk-thomas** [comment]
@eyildiz-ugoe commenting on an already closed ticket "doesn't work for me" with no context is not helpful. Please provide significantly more information if you would like help in troubleshooting what the problem in your case is.

**Comment by gavanderhoorn** [comment]
@eyildiz-ugoe already posted on ROS Answers about this, so his comment is a cross-post.

See [Ubuntu 16.04 Ros Kinect Installation Unmet Dependencies](https://answers.ros.org/question/305386).

After looking at the output of `apt-cache policy python-catkin-pkg python-catkin-pkg-modules` it looks like `apt` is somehow preferring to install the upstream versions in the Ubuntu repositories (note the higher priority in the `policy` output).

That clashes with the versions specced in some of the other pkgs, leading to the install being blocked.

I'm not sure why the Ubuntu repositories are given higher priority. On my system (also 16.04) they have the same priority leading to the newer `python-catkin-pkg` being installed.
