### ISSUE TITLE
version mismatch for hydro

### ISSUE THREAD

**Issue by YoheiKakiuchi** [ros-infrastructure/catkin_pkg#232]
In ubuntu precise ( 12.04 ),
python-catkin-pkg-modules depends python whose version is more than 2.7.5.
But version of python is 2.7.3.
Then, dependancy of python-catkin-pkg-modules can't be resolved.
Where is the version of dependancy set?

~~~
$ apt-cache show python-catkin-pkg-modules
Package: python-catkin-pkg-modules
Version: 0.4.7-1
Architecture: all
Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
Installed-Size: 242
Depends: python-argparse, python-dateutil, python-docutils, python-pyparsing, python:any (<< 2.8), python:any (>= 2.7.5-5~)
Conflicts: catkin, python-catkin-pkg (<< 0.3.0)
Replaces: python-catkin-pkg (<< 0.3.0)
Homepage: http://wiki.ros.org/catkin_pkg
Priority: optional
Section: python
Filename: pool/main/p/python-catkin-pkg-modules/python-catkin-pkg-modules_0.4.7-1_all.deb
Size: 40872
SHA256: 672ad193c82ff554173bb596f11ab64e30f71e50883c3e1eec8d6f8827e4eff8
SHA1: 59fb27298daf99f316784f8b634add2350185beb
MD5sum: d981b3034d4f47d211fba1258565b44f
Description: catkin package library
 Library for retrieving information about catkin packages.
~~~

**Comment by dirk-thomas** [comment]
Thanks for reporting the problem. Since Precise is EOL we don't test anything on that platform.

I think the problem comes from using the toolchain on Bionic to build the Debian packages. We use `stdeb` which at the end will invoke `dh_python2`. I guess the `python:any` version is defined based on the oldest version of Python on any non-EOL platform.

The same problem exists for the "modules" packages of `rosdistro` and `rospkg`.

**Comment by dirk-thomas** [comment]
We released new versions of the affected Python packages using the Xenial toolchain (which doesn't contain that "higher" version dependency):

* `catkin_pkg` 0.4.8
* `rospkg` 1.1.5
* `rosdistro` 0.6.9

This will likely be the last release of these Python packages targeting Precise (et al). I created PRs to these repos removing Ubuntu distros older than Trusty.

@YoheiKakiuchi Please comment here if these versions work successfully for you to make sure it does before stopping support for the platform.

**Comment by YoheiKakiuchi** [comment]
@dirk-thomas 
Thanks a lot

For python-rospkg-modules updated, still depends python:any (>= 2.7.5-5~)
~~~
/# aptitude show python-rospkg-modules
Package: python-rospkg-modules           
State: not installed
Version: 1.1.6-1
Priority: optional
Section: python
Maintainer: Ken Conley <kwc@willowgarage.com>
Architecture: all
Uncompressed Size: 132 k
Depends: python-catkin-pkg, python-yaml, python:any (< 2.8), python:any (>= 2.7.5-5~), lsb-release
Conflicts: python-rospkg (< 1.1.0), python-rospkg (< 1.1.0)
Replaces: python-rospkg (< 1.1.0), python-rospkg (< 1.1.0)
Description: ROS package library
        Library for retrieving information about ROS packages and stacks.
Homepage: http://wiki.ros.org/rospkg
~~~

**Comment by dirk-thomas** [comment]
1.1.7 will address this.

It turns our using the toolchain on Xenial is not a guarantee to get the "right" dependency. :disappointed:

**Comment by YoheiKakiuchi** [comment]
Problem fixed
Thanks
