### ISSUE TITLE
Cannot install catkin on debian buster

### ISSUE THREAD

**Issue by hadogenes** [ros-infrastructure/catkin_pkg#255]
When I run `apt install catkin`

> The following packages have unmet dependencies:
>  catkin : Depends: python-catkin-pkg but it is not going to be installed
>           Depends: python3-catkin-pkg but it is not going to be installed

When I try to add full deps in cmd `apt install catkin python-catkin-pkg python3-catkin-pkg python-catkin-pkg-modules python3-catkin-pkg-modules`

> The following packages have unmet dependencies:
>  python-catkin-pkg : Conflicts: catkin but 0.7.14-10 is to be installed
>                      Conflicts: python3-catkin-pkg but 0.4.12-100 is to be installed
>  python-catkin-pkg-modules : Conflicts: catkin but 0.7.14-10 is to be installed
>  python3-catkin-pkg : Conflicts: catkin but 0.7.14-10 is to be installed
>                       Conflicts: python-catkin-pkg but 0.4.12-100 is to be installed
>  python3-catkin-pkg-modules : Conflicts: catkin but 0.7.14-10 is to be installed

**Comment by dirk-thomas** [comment]
Please see http://wiki.ros.org/UpstreamPackages

**Comment by hadogenes** [comment]
and it says that I should install _desktop-full_, but it stops at catkin

**Comment by hadogenes** [comment]
Ok, my bad I didn't know that there are ros packages in system
