### ISSUE TITLE
catkin_install_python

### ISSUE THREAD

**Issue by swinterbotix** [ros-infrastructure/catkin_pkg#275]
Hi,

According to http://wiki.ros.org/catkin/CMakeLists.txt (Section 11.1) and http://docs.ros.org/melodic/api/catkin/html/howto/format2/installing_python.html, the proper way to install Python Executable Scripts is using the 'catkin_install_python' installation function. However, I noticed that the the CMakeLists template over [here](https://github.com/ros-infrastructure/catkin_pkg/blob/master/src/catkin_pkg/templates/CMakeLists.txt.in) (Line 156) uses the 'install' function. Shouldn't this be changed to 'catkin_install_python'?

Thanks,
Solomon

**Comment by dirk-thomas** [comment]
> Shouldn't this be changed to 'catkin_install_python'?

Yes. It would be great if you could contribute a pull request with that change.

**Comment by swinterbotix** [comment]
Created a Pull Request #276 to fix this issue
