### ISSUE TITLE
add caching results for repeated invocations to speedup repeated lookups

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/catkin_pkg#33]
This is now the slowest element when calling rosdep which is embedded inside rospack.  

This is a follow onto ros/rosdep#218

**Comment by dirk-thomas** [comment]
I will close this as "wontfix" since the API allows options for caching already () and crawling (at least once) is an inherent design decision in ROS 1.

Please comment with specific functions which should provide caching and this can be reconsidered.

**Comment by tfoote** [comment]
An example of using the caching API is here: https://github.com/ros/ros_comm/pull/542
